Added hierarchical shard selector
santanusinha/dropwizard-service-discovery pull request #24
Opened 2020-11-23 16:38 UTC by r0goyal

2020-11-26 09:09 UTC, santanusinha requested changes

2020-11-26 10:04 UTC, r0goyal commented on pom.xml
> +            <distributionManagement>
Yes. These POM changes would be reverted

2020-11-26 10:09 UTC, r0goyal commented on dropwizard-service-discovery-client/src/main/java/io/appform/dropwizard/discovery/client/selector/HierarchicalEnvironmentAwareShardSelector.java
> +                    .build());
Other option is to clone the incoming ShardInfo and then set the environment to the value derived here.

2020-11-26 10:19 UTC, r0goyal commented on dropwizard-service-discovery-client/src/main/java/io/appform/dropwizard/discovery/client/selector/HierarchicalEnvironmentAwareShardSelector.java
> +                return Lists.newArrayList();
Done

2020-11-26 10:23 UTC, r0goyal commented on pom.xml
> -                <groupId>org.codehaus.mojo</groupId>
This plugin has not been updated for a while now. Replacing this with jacoco for code coverage

2020-11-26 10:23 UTC, r0goyal commented on dropwizard-service-discovery-client/src/main/java/io/appform/dropwizard/discovery/client/selector/HierarchicalEnvironmentAwareShardSelector.java
> +    private static final String separator = ".";
Done

2021-01-11 11:18 UTC, r0goyal commented on dropwizard-service-discovery-client/src/main/java/io/appform/dropwizard/discovery/client/selector/HierarchicalEnvironmentAwareShardSelector.java
> +                    .build());
@santanusinha Would that be a good way to achieve this ?

2021-02-05 09:51 UTC, santanusinha approved these changes

2021-02-05 09:51 UTC, merged